### ISSUE TITLE
Bug with python2.6: AttributeError: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by bjolivot** [spotify/pyfg#18]
Lib is not working with python 2.6 & centos 6:

```
from pyFG import py23_compat
File "/usr/lib/python2.6/site-packages/pyFG/py23_compat.py", line 7
PY2 = sys.version_info.major == 2
AttributeError: 'tuple' object has no attribute 'major'
```

This is a common bug, PR is comming
