### PR TITLE
Fix #18

### LINKED ISSUE #18: Bug with python2.6: AttributeError: 'tuple' object has no attribute 'major'
Lib is not working with python 2.6 & centos 6:

```
from pyFG import py23_compat
File "/usr/lib/python2.6/site-packages/pyFG/py23_compat.py", line 7
PY2 = sys.version_info.major == 2
AttributeError: 'tuple' object has no attribute 'major'
```

This is a common bug, PR is comming

### PR DESCRIPTION
**Pull request by bjolivot**
This fix #18 bug.

Lib is not working with python 2.6 & centos 6:

```
from pyFG import py23_compat
File "/usr/lib/python2.6/site-packages/pyFG/py23_compat.py", line 7
PY2 = sys.version_info.major == 2
AttributeError: 'tuple' object has no attribute 'major'
```

### CODE REVIEW

**Comment by StefanLindblom** [comment]
Hi there!
Thanks for this.
Looks OK, but just for clarity I'm going to update the readme to say that other Python versions than 2.7 are not tested from our side.

/Stefan
